branches:
  only:
  - master
  - develop
skip_commits:
  files:
    - docs/*
    - '**/*.html'
image: Visual Studio 2017
build_script:
- cmd: >-
    @echo off

    cls

    If Not Exist src\.nuget\nuget.exe msbuild src\.nuget\NuGet.targets -Target:RestorePackages

    If Not Exist src\packages\FAKE\tools\fake.exe src\.nuget\nuget.exe Install FAKE -OutputDirectory "src\packages" -ExcludeVersion

    src\packages\FAKE\tools\fake.exe build.fsx %*
test:
  assemblies: src/Automatonymous.Tests/bin/Release/Automatonymous.Tests.dll
artifacts:
- path: build_artifacts/*.nupkg
- path: build_artifacts/*.xml

deploy:
- provider: NuGet
  name: Release
  api_key:
    secure: 0B2TmwiOnNW+CavGbvgr6S8WcuB2A/5enkf/ZrlRW+8Q8AwW5P9T7+B3QDAtYiEi
  on:
    branch: master

